### ISSUE TITLE
Instant crash in rpgstats 3.0.0+ for 1.16.4

### ISSUE THREAD

**Issue by DoctorArchives** [P03W/RPGStats#16]
Dec 19, 2020 4:04:49 PM net.devtech.arrp.ARRP onPreLaunch
SEVERE: I used the JSON to destroy the JSON
Exception in thread "main" java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'pconfig'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_2378.method_10234(class_2378.java:158)
	at net.minecraft.class_2378$$Lambda$192/1231493271.get(Unknown Source)
	at net.minecraft.class_2378.method_29110(class_2378.java:246)
	at net.minecraft.class_2378$$Lambda$1979/575166526.accept(Unknown Source)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676)
	at net.minecraft.class_2378.<clinit>(class_2378.java:245)
	at io.github.cottonmc.jankson.JanksonFactory.builder(JanksonFactory.java:85)
	at io.github.cottonmc.jankson.JanksonFactory.createJankson(JanksonFactory.java:159)
	at io.github.redstoneparadox.paradoxconfig.serialization.jankson.JanksonConfigSerializer.<init>(JanksonConfigSerializer.java:16)
	at io.github.redstoneparadox.nicetohave.config.Config.<clinit>(Config.java:13)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at io.github.redstoneparadox.paradoxconfig.util.ReflectionUtil.getClassForName(ReflectionUtil.java:13)
	at io.github.redstoneparadox.paradoxconfig.ParadoxConfig.initConfigs$paradox_config(ParadoxConfig.java:66)
	at io.github.redstoneparadox.paradoxconfig.ParadoxConfig.onPreLaunch(ParadoxConfig.java:21)
	at net.fabricmc.loader.launch.knot.Knot$$Lambda$88/1677207406.accept(Unknown Source)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 3 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Variable modifier method createArrowIfHasNix(Z)Z in rpgstats.mixins.json:BowArrowMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap rpgstats-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 26 more

Process crashed with exit code 1

**Comment by P03W** [comment]
Cant reproduce in dev environment, so likely a mod incompatibility, if you could post your mod list that would be helpful

**Comment by DoctorArchives** [comment]
@P03W
Sure, here: 
[FabricLoader] Loading 251 mods: roughlyenoughitems-api@5.8.10, deadtotems@0.1.1+1.16.3, step-height-entity-attribute@1.0.0, fabricloader@0.10.8, inventoryprofiles@0.4.2, nenchantfix@3.0.0, trinkets@2.6.7, crowdin-translate@1.2, gg_enchantments@1.1.1, colorunchained@1.1.1-1.16.4, mobs_attempt_parkour@0.2.1-1.16.3, fabric-dimensions-v1@2.0.1+9a6c75813a, edit_sign@2.1.3, cotton-client-commands@1.0.1+1.16-rc1, torohealth@1.16.4-fabric-3, adventurez@1.1.5, fabric-game-rule-api-v1@1.0.3+a4467d2a3a, fabric-api-base@0.2.0+ab87788d3a, dehydration@1.0.8, extra-discs@1.0.1, packages@1.1.1, playerabilitylib@1.2.1, waila@1.9.22, villagerhats@fabric-1.16.4-1.0.1, chat_heads@0.2.1+1.16.2, terraform-wood-api-v1@1.0.0+build.1, org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.4.0, woodenhoppers@1.0.0, moretotems@2.7.1, bunch-o-trinkets@1.0.1, villagers@1.0+1.16.3, bigextras@1.4, fabric-networking-v0@0.3.1+2a4333d33a, repurposed_structures@1.16.4-1.7.3, modmenu@1.14.13+build.19, flora-doubling@1.3.0+1.16.4-fabric, blur@2.0.0, dynamo_api@1.0.0+1.16.4, launchersmod@2.2.0, pconfig@0.3.6-alpha, org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.4.0, roughlyenoughitems-runtime@5.8.10, midnight-hats@2.0.1, autoswitch@2.11.5, headsdowndisplay@0.0.0, voyager@1.0.0, fabric-crash-report-info-v1@0.1.2+b7f9825d3a, loadcatcher@2.0.0, nbtcrafting@2.0.1+mc1.16.4, betterweather@1.0.0, fabric-key-binding-api-v1@1.0.1+730711c63a, com_typesafe_config@1.4.0, compactstatuseffects@1.2.3, trapexpansion@1.3.2, magna@1.4.2-1.16.2, staticdata@1.1.2, breakprogress@1.0.1, adorn@1.12.2+1.16.4, conjuring@0.1.3-beta, fabric-networking-api-v1@1.0.0+4358fbc63a, cleanview@1.16.4-v1-fabric, org_jetbrains_annotations@20.0.0, gentlepicking@1.0.2, parchment@1.0.2+1.15.2, oaktree@0.4.2-beta, pulverizer_mod@1.0, grindenchantments@1.1.3+1.16.3, better_wandering_trader@1.6.2, vanillaexcavators@1.1.0, fabric-structure-api-v1@1.1.1+f1d8af063a, maelstrom_library@0.4.1, unsaddlepigs@1.0.1-mc1.16.4-fabric, fabric-object-builder-api-v1@1.9.2+6a2618f53a, ringsofascension@1.1.1, mcdw@2.2.3, fallingleaves@1.2, infinitywaterbucket@1.0.3.2-compat-mc1.16.4-fabric, terraform-config-api-v1@1.0.0+build.1, tinytweaks@1.1.2, fabric-rendering-data-attachment-v1@0.1.4+6a2618f53a, mcda@0.7.7, enchants@1.0.0, seasons@1.0.3-BETA, terraform-surfaces-api-v1@1.0.0+build.1, reach-entity-attributes@1.0.2, strawdummy@1.4.0, fabric-lifecycle-events-v1@1.2.0+74cc3b203a, fabric-loot-tables-v1@1.0.1+6a2618f53a, mcf-easyfeed@1.3.0, libblockattributes_core@0.8.4, libnetworkstack@0.4.1, terraform-biome-builder-api-v1@1.0.0+build.1, minecraft@1.16.4, horsestatsvanilla@4.1.4, xpstorage@1.2+1.16.4, jankson@3.0.1+j1.2.0, fabric-command-api-v1@1.0.9+6a2618f53a, illuminations@1.3.1, sneak-through-berries@1.1.0+1.16.4-fabric, nicetohave@1.3.5, miniextras@1.2.1, fabric-renderer-indigo@0.4.3+6a2618f53a, mechanicaltech@0.2.0+1.16.4, libgui@3.2.2+1.16.3, netherite_nugget@1.0.2, fabric-rendering-v0@1.1.1+6a2618f53a, fabric-rendering-v1@1.4.0+6a2618f53a, givemehats@1.4, autoconfig1u@3.3.1, fabric-tag-extensions-v0@1.1.0+e77439c73a, expcontainer@1.9, blue_endless_jankson@1.2.0, can-i-mine-this-block@1.0.2, homecamp@1.0.2, kirin@1.7-1.16.2, economical_villager_trading@1.0.2+MC1.16.4, dragonloot@1.0.3, fabric-events-lifecycle-v0@0.2.0+6a2618f53a, inventorypause@1.0.4, climbable@0.2.0, fabrictailor@1.4.0-1.16.4, flamingo_ooo@1.0.4-MC1.16.3-fabric, fabric-keybindings-v0@0.2.0+6a2618f53a, notenoughcrashes@2.1.4+1.16.4, fishonaleash@1.16.3-1.0.0, satin@1.5.1, hotfurnace@1.1.1, adapaxels@1.0.5+1.16.4, superaxes@2.0.9, craftingpad@1.16.4-fabric0.25.1-1.0.5, eldritch_mobs@1.5.4, rpgstats@3.0.0+1.16.4, villagernames@1.5.2, xaeroworldmap@1.11.4, beaconsforall@1.4.0-1.16.4, diggusmaximus@1.4.2-1.16.3, fabrication@1.2.3_02, blackstonetools@1.2.0+1.16.1, continuebutton@1.0.2, beebetter@1.8.0-1.16.4, org_jetbrains_kotlin_kotlin-stdlib@1.4.0, colorfulcolumns@1.0.0, fabric-blockrenderlayer-v1@1.1.4+6a2618f53a, killerbee@1.0, cameraoverhaul@1.0-fabric-1.16, fabric@0.28.3+1.16, netherite_plus@1.1.0, smallendermen@1.1.0, engilib@1.0.0+1.16.4, autoswitch-api@1.0.0, libmultipart@0.4.3, fabric-screen-handler-api-v1@1.1.0+6a2618f53a, blastproof_netherite@1.16.4, greater_eye@1.1.3, columns@1.1.1, fabric-tool-attribute-api-v1@1.2.5+6a2618f53a, bloodparticles@1.1.1, plantable_pots@1.0.0, autofish@0.9.1, angerable-patch@1.1.0-1.16.4, terraform-tree-api-v1@1.0.0+build.1, org_aeonbits_owner_owner@1.0.10, rare-ice@0.2.2, cloth-client-events-v0@1.4.5, fabric-events-interaction-v0@0.4.1+6a2618f53a, houraielixir@1.16.4-1, fabric-language-kotlin@1.4.0+build.1, cloth-config2@4.8.3, sturdygold@0.1.0, advancednbttooltip@1.0.6+build.2-1.16.4, org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.3.9, sorcerycraft@1.2.9+1.16.4, fabric-resource-loader-v0@0.3.2+1944f3e03a, spawnlanterns@1.0.1, chainmail@0.5.0, org_jetbrains_kotlin_kotlin-reflect@1.4.0, expandedstorage@5.6.31, elytraboosters@1.1.0, wishing-well@1.1.1-1.16.2, cardinal-components-entity@2.7.9, fabric-registry-sync-v0@0.7.3+be155ae23a, cherishedworlds@1.3.0-1.16.4, fabric-commands-v0@0.2.0+6a2618f53a, cardinal-components-base@2.7.9, cpas@1.1.1+1.16.4, fabric-mining-levels-v0@0.1.2+6a2618f53a, pinesbarrels@1.0.1, earthtojavamobs@1.4.0+1.16.4, libmultipart_deps_container@0.4.3, fabric-models-v0@0.1.1+6a2618f53a, fabric-item-groups-v0@0.2.1+6a2618f53a, extraalchemy@1.3.1, shulkerboxtooltip@2.3.3+1.16.4, fabric-renderer-api-v1@0.3.3+6a2618f53a, environmentz@1.0.7, libcd@3.0.3+1.16.3, vanilla-hammers@3.0.1-1.16.3, allure@1.2.8, crawl@0.8.1, fabric-containers-v0@0.1.9+a03e98793a, particlerain@1.1.1, accurateblockplacement@1.0.8, redbits@1.5.0, waystones@1.0.10, artifacts@2.0.2+1.16.4-fabric, mm@2.1, cloth-dynamic-registry-api-v1@1.2.1, campanion@1.3.1+build.51, fabric-textures-v0@1.0.5+a4467d2a3a, cardinal-components-item@2.7.9, sojurn@b1.1, fabric-rendering-fluids-v1@0.1.12+6a2618f53a, bedspreads@1.3.1-1.16.4, notchify@0.3.0, traverse@3.0.3+build.13, fabric-renderer-registries-v1@2.2.0+f8ac1db23a, roundtrees@1.0.0, curses@1.5.1, effect@1.0.0, fabric-particles-v1@0.2.2+6a2618f53a, vanilla_parts@1.1.4+1.16.3, fabric-networking-blockentity-v0@0.2.7+a03e98793a, roughlyenoughitems-default-plugin@5.8.10, cloth-basic-math@0.5.1, static-content@1.0.1-1.16.2, stuffz@2.2.2, verticalredstone@1.2.0-beta1, fabric-item-api-v1@1.2.0+6a2618f53a, roughlyenoughitems@5.8.10, rocks@1.2.2, kyrptconfig@1.1.4-1.16, terraform-overworld-biome-extensions-api-v1@1.0.0+build.1, fabric-content-registries-v0@0.2.0+e77439c73a, tiered@1.2.0-beta-1.16.4, fabric-biome-api-v1@3.1.0+2e23b97c3a, optifabric@1.8.13, advanced_runtime_resource_pack@0.2.6, enchantedtooltips@1.3.4-1.16, hplus@1.0.10, randomblockplacement@1.16.4-fabric0.25.1-1.1.1, custom-crosshair-mod@1.0.3-fabric, lakeside@1.0.3+1.16.4, zoob@2.5.0, carrier@1.6.1, golem@1.3.1, projectsavethepets@1.0.2+minecraft-1.16.4, xaerobetterpvp@20.29.1, libstructure@1.5, fabric-object-builders-v0@0.7.1+6a2618f53a, camp_fires_cook_mobs@1.1.5+MC1.16.2-1.16.4, presencefootsteps@r28+1.16.2

**Comment by P03W** [comment]
Apparently not mod incompatibility, something is going wrong with mixin exports, ill try to figure this out asap

**Comment by P03W** [comment]
Oop, found the issue, should have a fix out within 5-15 minutes, thanks for taking the time to actually report an issue!

**Comment by P03W** [comment]
3.0.1 fixes this

Again, thanks for actually taking time to report this!

**Comment by DoctorArchives** [comment]
> Oop, found the issue, should have a fix out within 5-15 minutes, thanks for taking the time to actually report an issue!
@P03W 

No problem! I've found that reaching out to the actual devs of a mod is probably the best way to fix issues if you can't seem to do anything or are clueless.

**Comment by DoctorArchives** [comment]
> 3.0.1 fixes this
Thanks!
