### ISSUE TITLE
3.0.2+1.16.4 Client crash

### ISSUE THREAD

**Issue by kotx** [P03W/RPGStats#17]
When using [Extra Origins](https://github.com/MoriyaShiine/extra-origins/issues/21) with the class "Glass Golem", right-clicking with a potion causes this mod to crash the game. 

I am certain this is an issue with RPGStats, because all Extra Origins does is [disable status effects for the player](https://github.com/MoriyaShiine/extra-origins/blob/fae52d46373a8f123815a2d1c90b91d553904fa1/src/main/java/moriyashiine/extraorigins/mixin/LivingEntityMixin.java#L96) (by making `canHaveStatusEffect` and `isAffectedBySplashPotions` return false, unless the effect is bad omen).

RPGStats most likely crashes when `canHasStatusEffect` is false. What's strange is, the crash occurs when right-clicking with a non-splash potion instead of after drinking it. 

Crash report:
```
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 12/23/20 12:21 PM
Description: Unexpected error

java.lang.ClassCastException: net.minecraft.class_746 cannot be cast to net.minecraft.class_3222
	at net.minecraft.class_1812.handler$zie000$getUseTime(class_1812.java:545)
	at net.minecraft.class_1812.method_7881(class_1812.java)
	at net.minecraft.class_1799.method_7935(class_1799.java:491)
	at net.minecraft.class_1309.method_6019(class_1309.java:2864)
	at net.minecraft.class_746.method_6019(class_746.java:528)
	at net.minecraft.class_5328.method_29282(class_5328.java:16)
	at net.minecraft.class_1812.method_7836(class_1812.java:81)
	at net.minecraft.class_1799.method_7913(class_1799.java:239)
	at net.minecraft.class_636.method_2919(class_636.java:349)
	at net.minecraft.class_310.method_1583(class_310.java:1472)
	at net.minecraft.class_310.method_1508(class_310.java:1709)
	at net.minecraft.class_310.method_1574(class_310.java:1534)
	at net.minecraft.class_310.method_1523(class_310.java:1021)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at link.infra.jumploader.Jumploader.onLoad(Jumploader.java:171)
	at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53)
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$58/692331943.accept(Unknown Source)
	at java.util.HashMap$Values.forEach(HashMap.java:972)
	at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:56)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:76)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_1812.handler$zie000$getUseTime(class_1812.java:545)
	at net.minecraft.class_1812.method_7881(class_1812.java)
	at net.minecraft.class_1799.method_7935(class_1799.java:491)
	at net.minecraft.class_1309.method_6019(class_1309.java:2864)
	at net.minecraft.class_746.method_6019(class_746.java:528)
	at net.minecraft.class_5328.method_29282(class_5328.java:16)
	at net.minecraft.class_1812.method_7836(class_1812.java:81)
	at net.minecraft.class_1799.method_7913(class_1799.java:239)
	at net.minecraft.class_636.method_2919(class_636.java:349)
	at net.minecraft.class_310.method_1583(class_310.java:1472)
	at net.minecraft.class_310.method_1508(class_310.java:1709)

-- Affected level --
Details:
	All players: 1 total; [class_746['kotuwu'/200, l='ClientLevel', x=260.00, y=72.00, z=-292.48]]
	Chunk stats: Client Chunk Cache: 841, 500
	Level dimension: minecraft:overworld
	Level spawn location: World: (240,69,-256), Chunk: (at 0,4,0 in 15,-16; contains blocks 240,0,-256 to 255,255,-241), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 1361 game time, 1361 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:704)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at link.infra.jumploader.Jumploader.onLoad(Jumploader.java:171)
	at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53)
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$58/692331943.accept(Unknown Source)
	at java.util.HashMap$Values.forEach(HashMap.java:972)
	at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:56)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:76)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 701306792 bytes (668 MB) / 1888485376 bytes (1801 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 12
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m -XX:PermSize=256m
	Fabric Mods: 
		autoconfig1u: Auto Config v1 Updated 3.3.1
		cardinal-components-base: Cardinal Components API (base) 2.7.9
		cardinal-components-entity: Cardinal Components API (entities) 2.7.9
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.8.1
		extraorigins: Extra Origins 1.16.4-5
		fabric: Fabric API 0.28.3+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+6a2618f53a
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+6a2618f53a
		fabric-containers-v0: Fabric Containers (v0) 0.1.9+a03e98793a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+6a2618f53a
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+6a2618f53a
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+6a2618f53a
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+ffb68a873a
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+6a2618f53a
		fabric-models-v0: Fabric Models (v0) 0.1.1+6a2618f53a
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+4358fbc63a
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.7+a03e98793a
		fabric-networking-v0: Fabric Networking (v0) 0.3.1+2a4333d33a
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
		fabric-particles-v1: fabric-particles-v1 0.2.2+6a2618f53a
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.3+be155ae23a
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+6a2618f53a
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+6a2618f53a
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+6a2618f53a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+6a2618f53a
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+6a2618f53a
		fabric-rendering-v1: Fabric Rendering (v1) 1.4.0+6a2618f53a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.2+1944f3e03a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.1+f1d8af063a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+6a2618f53a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
		fabricloader: Fabric Loader 0.10.8
		fallflyinglib: FallFlyingLib 1.1.0
		jankson: Jankson 3.0.1+j1.2.0
		jumploader: Jumploader 2.1.2
		libgui: LibGui 3.2.2+1.16.3
		minecraft: Minecraft 1.16.4
		origins: Origins 0.4.5
		origins-classes: Origins: Classes 1.1.0
		pehkui: Pehkui 1.6.2+1.16.3
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		rpgstats: RPGStats 3.0.2+1.16.4
	Launched Version: Jumploader
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 460.20, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: fabric/fabric-renderer-api-v1, fabric/fallflyinglib, fabric/fabric-keybindings-v0, fabric/fabricloader, fabric/fabric-containers-v0, fabric/pehkui, fabric/fabric-object-builder-api-v1, fabric/fabric-game-rule-api-v1, fabric/fabric-api-base, fabric/fabric-rendering-data-attachment-v1, fabric/fabric-textures-v0, fabric/fabric-rendering-fluids-v1, fabric/fabric-blockrenderlayer-v1, fabric/fabric-lifecycle-events-v1, fabric/fabric-renderer-registries-v1, fabric/fabric-loot-tables-v1, fabric/fabric, fabric/fabric-networking-v0, fabric/fabric-networking-blockentity-v0, fabric/fabric-screen-handler-api-v1, fabric/fabric-command-api-v1, fabric/origins-classes, fabric/fabric-tool-attribute-api-v1, fabric/extraorigins, fabric/fabric-renderer-indigo, fabric/fabric-item-api-v1, fabric/fabric-crash-report-info-v1, fabric/fabric-events-interaction-v0, fabric/origins, fabric/fabric-rendering-v0, fabric/fabric-rendering-v1, fabric/fabric-key-binding-api-v1, fabric/cloth-config2, fabric/autoconfig1u, fabric/fabric-resource-loader-v0, fabric/fabric-content-registries-v0, fabric/fabric-tag-extensions-v0, fabric/fabric-biome-api-v1, fabric/fabric-registry-sync-v0, fabric/fabric-mining-levels-v0, fabric/fabric-networking-api-v1, fabric/fabric-events-lifecycle-v0, fabric/fabric-models-v0, fabric/fabric-item-groups-v0, fabric/fabric-object-builders-v0
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor 
```

**Comment by superon** [comment]
yes, i'm seeing this too, i did have origins also running but have since tested with everything except for rpgstats disabled https://pastebin.com/ULcPhjZu  currently importing backwards to see if a recent version doesn't have this problem..

**Comment by superon** [comment]
ok, looks like that latest one that doesn't have this issue is rpgstats-2.3.2+1.16.3

**Comment by P03W** [comment]
Thanks for the info! Looking into it

**Comment by P03W** [comment]
Well, your link is giving me a 404 (mixin seems to have been removed?) but it seems its trying to cast a ClientPlayerEntity to a ServerPlayerEntity

Ill add a sanity check for cases like this (although that logic probably shouldn't be called client side, but thats an origins problem :p)

**Comment by superon** [comment]
https://pastebin.com/ULcPhjZu link works for me.. also i did test this with origins disabled

**Comment by P03W** [comment]
Sorry, not your link, I meant https://github.com/MoriyaShiine/extra-origins/blob/master/src/main/java/moriyashiine/extraorigins/mixin/InorganicHandler.java#L58

**Comment by superon** [comment]
a ha, idk what's going on at the best of times :/

**Comment by P03W** [comment]
Will be fixed in next update

Seems to be an issue when adding client compat, ill go through and make sure there arent any other bugs like this waiting :p

**Comment by P03W** [comment]
New curseforge version should resolve this, could either (or both) of you check?

**Comment by superon** [comment]
i will for sure

**Comment by kotx** [comment]
> 
> 
> Sorry, not your link, I meant https://github.com/MoriyaShiine/extra-origins/blob/master/src/main/java/moriyashiine/extraorigins/mixin/InorganicHandler.java#L58

Whoops, here's the link: https://github.com/MoriyaShiine/extra-origins/blob/fae52d46373a8f123815a2d1c90b91d553904fa1/src/main/java/moriyashiine/extraorigins/mixin/LivingEntityMixin.java#L96

**Comment by superon** [comment]
works at least for the bottle and for the client :) 
.. testing server soon, should i hold off until you've had a good look at the moriya thing?

**Comment by P03W** [comment]
Nah I added sanity checks to all my mixins, feel free to check everything

**Comment by superon** [comment]
initial testing says this now produces no crash at least for me, will give it a more prolonged assault in around 12 hours, thanks for the work

**Comment by P03W** [comment]
Going to assume this is fixed for now, thanks for reporting!

**Comment by superon** [comment]
👍
