### ISSUE TITLE
Cannot bone meal underwater

### ISSUE THREAD

**Issue by BoredBrownBear** [P03W/RPGStats#58]
I'm on 4.0.5 version.

We were having issues not being able to bone meal under water. I removed the mod and we were able to bonemeal again underwater so I think the problem is with the mod.

**Comment by BoredBrownBear** [comment]
```
[Server thread/FATAL]: Error executing task on Server

java.lang.ArithmeticException: / by zero

at net.minecraft.class_1752.handler$bce000$groundEffectiveness(class_1752.java:544) ~[intermediary-server.jar:?]

at net.minecraft.class_1752.method_7719(class_1752.java) ~[intermediary-server.jar:?]

at net.minecraft.class_1752.method_7884(class_1752.java:54) ~[intermediary-server.jar:?]

at net.minecraft.class_1799.method_7981(class_1799.java:227) ~[intermediary-server.jar:?]

at net.minecraft.class_3225.method_14262(class_3225.java:348) ~[intermediary-server.jar:?]

at net.minecraft.class_3244.method_12046(class_3244.java:1040) ~[intermediary-server.jar:?]

at net.minecraft.class_2885.method_12547(class_2885.java:36) ~[intermediary-server.jar:?]

at net.minecraft.class_2885.method_11054(class_2885.java:10) ~[intermediary-server.jar:?]

at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]

at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]

at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]

at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]

at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-server.jar:?]

at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-server.jar:?]

at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]

at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-server.jar:?]

at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-server.jar:?]

at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]

at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722) ~[intermediary-server.jar:?]

at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) ~[intermediary-server.jar:?]

at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]

at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by P03W** [comment]
Weird, shouldn't prevent anything

I'll look into it though

**Comment by P03W** [comment]
Does 4.1.3 resolve this?

**Comment by BoredBrownBear** [comment]
I can test 4.1.3 if it's compatible with 1.16.5, our server's current version. With that said, is it compatible?

**Comment by P03W** [comment]
it is not, no

**Comment by BoredBrownBear** [comment]
Okay, I'll just try to backport your code changes for the raised function and compile it later. As for 1.17 I'll try it later as well.

**Comment by BoredBrownBear** [comment]
I have yet to test 1.17, but seeing how backporting the fix made the error go away, I'm assuming it to be fixed already.

Here's the backport I made, in case you want to release an updated version for 1.16.5: https://github.com/BoredBrownBear/RPGStats/tree/1.16.5

Although I did remove Simple Harvest and Harvest Scythes compatibility code since I wasn't using them, and they were causing problems when I was trying to compile.

**Comment by P03W** [comment]
Going to assume this is fixed at this point, if anyone is still having this issue feel free to comment here
