### ISSUE TITLE
Game crashes when I try to run it: exit code -1

### ISSUE THREAD

**Issue by beautiful-lunatic** [P03W/RPGStats#65]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2021-07-05, 8:45 p.m.
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'rpgstats'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.NoClassDefFoundError: io/github/cottonmc/cotton/gui/GuiDescription
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:466)
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.lambda$getOrCreate$0(EntrypointStorage.java:106)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:104)
	at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:191)
	at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more
Caused by: java.lang.ClassNotFoundException: io.github.cottonmc.cotton.gui.GuiDescription
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:175)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 20 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.<init>(class_310.java:459)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.17
	Minecraft Version ID: 1.17
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 453729896 bytes (432 MiB) / 1509949440 bytes (1440 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 1.80
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) UHD Graphics 620
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x5917
	Graphics card #0 versionInfo: DriverVersion=30.0.100.9667
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: LPDDR3
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: LPDDR3
	Virtual memory max (MB): 10737.14
	Virtual memory used (MB): 6302.28
	Swap memory total (MB): 2688.00
	Swap memory used (MB): 233.74
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advanced-xray-fabric: Advanced XRay (Fabric) 0.6.0-build.8
		adventurez: AdventureZ 1.2.7
		allstackable: All Stackable 1.4.1-1.17
		apoli: Apoli 1.0.3
		apugli: Apugli 1.0.2
		architectury: Architectury 2.0.8
		artifality: Artifality 0.3.0
		boostedbrightness: Boosted Brightness 2.0.0
		calio: Calio 1.0.1
		cardinal-components: Cardinal Components API 3.0.0
		cardinal-components-base: Cardinal Components API (base) 3.0.0
		cardinal-components-block: Cardinal Components API (blocks) 3.0.0
		cardinal-components-chunk: Cardinal Components API (chunks) 3.0.0
		cardinal-components-entity: Cardinal Components API (entities) 3.0.0
		cardinal-components-item: Cardinal Components API (items) 3.0.0
		cardinal-components-level: Cardinal Components API (world saves) 3.0.0
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 3.0.0
		cardinal-components-util: Cardinal Components API (utilities) 3.0.0
		cardinal-components-world: Cardinal Components API (worlds) 3.0.0
		charm: Charm 3.1.6
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 5.0.34
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		consularsorigins: Consulars Origins 1.17-1.0.0
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.3
		extraorigins: Extra Origins 1.17-1
		fabric: Fabric API 0.35.2+1.17
		fabric-api-base: Fabric API Base 0.3.0+8d89ed5432
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.1.0+1d383bb63d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea83d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b44633d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+a02b44633d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa3d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b44633d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b44633d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da3103d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.10+a02b44633d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b44633d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.8+a02b44633d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa3d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+a02b44633d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b44633d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab61213d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b44633d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e3d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b44633d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa3d
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b44633d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.11+b7ab61213d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b44633d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa3d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab61213d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b44633d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b44633d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee3d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.3+676f40fa3d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b44633d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b44633d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b44633d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b44633d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa3d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b44633d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab61213d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b44633d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+e36969833d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b44633d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b44633d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab61213d
		fabricasmtools: Fabric ASM tools 0.4.0
		fabricloader: Fabric Loader 0.11.6
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fallingtree: FallingTree 2.12.1
		fourinchknife-trueinfinity: True Infinity 1.2.0
		gobber2: Gobber2 2.4.22
		identity: Identity 1.14.2-beta-1.17
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		libninepatch: LibNinePatch 1.1.0
		limitless: limitless 1.3.0
		lithium: Lithium 0.7.1
		minecraft: Minecraft 1.17
		moborigins: Mob Origins 1.5.0
		modmenu: Mod Menu 2.0.2
		more_gems: More Gems 1.2.16
		mostructures: Mo' Structures 1.2.0-1.17
		net_gudenau_lib_unsafe: unsafe 1.4.3
		npcvariety: NPC Variety 2.0.0
		nyfsquivers: Nyf's Quivers Fabric-0.2.3
		omega-config: OmegaConfig 1.0.8
		origins: Origins 1.0.2
		origins-classes: Origins: Classes 1.2.1
		pehkui: Pehkui 2.2.1+1.14.4-1.17
		playerabilitylib: Pal 1.3.0-nightly.1.17-rc1
		pugh_lib: Pugh Lib 1.1.3
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		repurposed_structures: Repurposed Structures 2.0.0+1.17.0
		roughlyenoughitems: Roughly Enough Items 6.0.250-alpha
		rpgstats: RPGStats 4.1.5+1.17.1-rc1
		stoneholm: Stoneholm 1.3
		toomanyorigins: TooManyOrigins 0.1.3b
		torohealth: ToroHealth Damage Indicators 1.17-fabric-7
		trinkets: Trinkets 3.0.0
		user11681_reflect: reflect 1.12.0
		user11681_shortcode: shortcode 0.4.0
		xaeroworldmap: Xaero's World Map 1.14.5.1
	Launched Version: fabric-loader-0.11.6-1.17
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by P03W** [comment]
The templates do not exist for you to delete the entire thing, please use them in the future

Is this an issue with only RPGStats?

**Comment by beautiful-lunatic** [comment]
> The templates do not exist for you to delete the entire thing, please use them in the future
> 
> Is this an issue with only RPGStats?

What do you mean by templates and deleting? I'm still kind of new with posting issues to Github from mods. 

And It crashes when I try to run the game and gives me that code.

**Comment by P03W** [comment]
When you created the issue there was a significant amount of text already there, your supposed to fill it out

Im asking if this is an issue when you have only RPGStats or only when you add other mods

**Comment by P03W** [comment]
Is this still an issue in 4.1.6?

**Comment by P03W** [comment]
Assuming issue fixed
